### PR TITLE
test: fix `TestAcceptBlock` flake

### LINKED ISSUE #133: Fix `TestAcceptBlock` flake
See https://github.com/ava-labs/strevm/actions/runs/21603826370/job/62256297607

### PR DESCRIPTION
**Pull request by JonathanOppenheimer**
Closes #133. 

Occasionally this test will fail with 

```
Error: Should be zero, but was 2
Messages: initial in-memory block count
```

Under CI,  previous tests' finalizers can take >100ms to run, which does not give the GC adequate time to run -- this gives the GC ample time.

### CODE REVIEW

File: sae/vm_test.go [hunk 1]
```diff
@@ -547,10 +547,14 @@ func TestSyntacticBlockChecks(t *testing.T) {
 }
 
 func TestAcceptBlock(t *testing.T) {
+	// Wait for GC finalizers from previous tests to run. Blocks are tracked via
+	// runtime.AddCleanup, which runs asynchronously during GC. In CI environments,
+	// finalizers can take longer to run, so we use a generous timeout to ensure
+	// we start with a clean block count. Zero!
```
Comment (StephenButtolph) [inline sae/vm_test.go]:
```suggestion
	// In resource constrained environments, finalizers can take a long time to
	// run, so we need to use a generous timeout.
```
